_core:
  default_config_hash: u2tWnDfo9G_VSwUfP_APpK_z3VWWU6pCjoWmx4J0Amk
defaults:
  amount:
    status: true
    settings:
      amount: 5
  created:
    status: false
    settings:
      age: 1
  drafts:
    status: false
    settings:
      age: 1
  only_drafts:
    status: false
    settings:
      age: 0
disable_automatic_queueing: false
verbose_log: true
