_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: 0b4d0792-a508-4444-af95-0fe4e65a4c38
name: Vivacity
mail: glenshewchuck@gmail.com
slogan: ''
page:
  403: /user/login
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
